### ISSUE TITLE
It cannot parse files where we have parenthesis in the imports

### ISSUE THREAD

**Issue by SamuelNLP** [HadiZakiAlQattan/pycln#2]
Example from one of my projects:

```python
from nes_ai.ai.genome import (
    Activation,
    ConnectionGene,
    InnovationCollection,
    NodeGene,
    TypeNodeGene,
)
```

I am getting:

> Parenthesis is not closed.
> Error while parsing the file!

**Comment by HadiZakiAlQattan** [comment]
That's because of the limitation of Regex (The project based on regex), this issue will be solved after using the Python AST approach.

I'll work on it as soon as possible, Thank you for the feedback.

**Comment by SamuelNLP** [comment]
Nice, thanks for the module. :)
